<?php
class FieldtypeCountrySelect extends FieldtypeText {

	public function init() {
		// $this->addStyle("custom.css");
		// $this->addScript("custom.js");
		// $this->addHookAfter("class::function", $this, "yourFunction");
	}

	public function sanitizeValue(Page $page, Field $field, $value) {
		
	}

	public function ___wakeupValue(Page $page, Field $field, $value) {
		
	}

	public function ___formatValue(Page $page, Field $field, $value) {
		
	}

	public function getInputfield(Page $page, Field $field) {
		
	}

	public function getDatabaseSchema(Field $field) {
		
	}

}